site_name: OptimumKinematics Help File

nav:
    - Home: index.md
    - Welcome: welcome.md
    - Introduction: 
      - Introduction: 1_Introduction/1_Introduction.md
      - Installation Requirements: 1_Introduction/A_Installation_Requirements.md
    - Quick Start: 
      - Launching the Application: 2_Quick_Start/A_Launching_the_Application.md
      - Options Menu: 2_Quick_Start/B_Options_Menu.md
      - Design Overview: 2_Quick_Start/C_Design_Overview.md
      

theme: readthedocs

use_directory_urls: false